---
apiVersion: v1
kind: Secret
metadata:
  name: serenamarie125-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/serenamarie125-frontend-gitops
